const services=[{"title": "Math Tutoring", "price": 30, "duration": "50 minutes", "location": "Online"}, {"title": "Writing Coaching", "price": 30, "duration": "50 minutes", "location": "Online"}, {"title": "English & Language Arts", "price": 30, "duration": "50 minutes", "location": "Online"}, {"title": "Foundational Culinary Arts", "price": 660, "duration": "6 weeks \u00b7 2.5 hours/week", "location": "Kea\u02bbau, Hawai\u02bbi", "course": true}, {"title": "The Way of Herbs", "price": 35, "duration": "90 minutes", "location": "Kea\u02bbau, Hawai\u02bbi"}, {"title": "Puna Gardening", "price": 40, "duration": "2 hours", "location": "Kea\u02bbau, Hawai\u02bbi"}, {"title": "Plant-Based Culinary Arts", "price": 625, "duration": "6 weeks \u00b7 2.5 hours/week", "location": "Kea\u02bbau, Hawai\u02bbi", "course": true}, {"title": "The Art of Bread Making", "price": 520, "duration": "6 weeks \u00b7 2 hours/week", "location": "Kea\u02bbau, Hawai\u02bbi", "course": true}];
const el=id=>document.getElementById(id);
services.forEach((s,i)=>{const o=document.createElement('option');o.value=i;o.textContent=s.title;el('program').append(o)});
const initial=Number(new URLSearchParams(location.search).get('program'));el('program').value=Number.isInteger(initial)&&initial>=0&&initial<services.length?initial:0;
const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);const date=[tomorrow.getFullYear(),String(tomorrow.getMonth()+1).padStart(2,'0'),String(tomorrow.getDate()).padStart(2,'0')].join('-');el('date').value=date;el('date').min=date;
function update(){const s=services[el('program').value];el('summaryTitle').textContent=s.title;el('summaryDetails').textContent=s.duration+' · '+s.location;el('summaryPrice').textContent='$'+s.price.toFixed(2)+(s.course?' / six-week course / person':s.location==='Online'?' / session':' / person');if(s.location!=='Online')el('timezone').value='Pacific/Honolulu'}
el('program').addEventListener('change',update);update();
el('bookingForm').addEventListener('submit',event=>{event.preventDefault();const s=services[el('program').value];const dateLabel=new Date(el('date').value+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'});const details=[['Program',s.title],['Learner',el('learner').value],['Example date',dateLabel],['Example time',el('time').value+' · '+el('timezone').value],['Location',s.location],['Duration',s.duration],['Sample price','$'+s.price.toFixed(2)+(s.course?' / six-week course / person':s.location==='Online'?' / session':' / person')],['Payment','Not charged — demonstration only']];el('confirmationDetails').replaceChildren();details.forEach(([key,value])=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;dd.textContent=value;el('confirmationDetails').append(dt,dd)});el('bookingForm').hidden=true;el('confirmation').hidden=false;el('confirmation').focus()});
el('edit').addEventListener('click',()=>{el('confirmation').hidden=true;el('bookingForm').hidden=false;el('program').focus()});
